apiVersion: apps/v1
kind: Deployment
metadata:
  name: lang-portal-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lang-portal-api
  template:
    metadata:
      labels:
        app: lang-portal-api
    spec:
      containers:
      - name: lang-portal-api
        image: lang-portal-api:latest
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: lang-portal-secrets
              key: database-url 