docarray[full]
fastapi
huggingface_hub
langchain
langchain_community
opentelemetry-api
opentelemetry-exporter-otlp
opentelemetry-sdk
shortuuid
uvicorn
prometheus-client
aiohttp
pydantic
prometheus_fastapi_instrumentator
predictionguard
boto3
botocore
torch
openai
